### ISSUE TITLE
Italic of CJK characters not work

### ISSUE THREAD

**Issue by cody1996** [adobe-fonts/source-han-mono#2]
It doesn't work when I set Chinese characters to italics. Like the picture below:

![Snipaste_2020-05-16_10-11-29](https://user-images.githubusercontent.com/17870939/82108981-6d550180-9765-11ea-9c70-8fd84290dc6b.png)

Is this a issue? Or is it designed like this?

**Comment by frankrolf** [comment]
This is likely intentional. If you look at the Latin, you will notice that Source Han Mono is the only example that uses real Italic shapes (the a, for example).
All the other examples are automatically skewed, with both Latin and CJK characters distorted.

**Comment by punchcutter** [comment]
Yes this is intentional and is explained on page 6 of [SourceHanMonoReadMe.pdf](https://github.com/adobe-fonts/source-han-mono/blob/master/SourceHanMonoReadMe.pdf)

**Comment by cody1996** [comment]
@frankrolf @punchcutter First of all thank you for your reply.
In fact, I have read the readme file before submitting this issue, but I did not fully understand it.
Does this mean that the software needs to support the automatic skew function, which is not supported by Intellij IDEA and Microsoft Word for the time being?
Or am I missing some steps to install and configure?

**Comment by punchcutter** [comment]
Most software, and especially Microsoft Word, automatically skew the shapes if the font does not have an Italic version. The only reason it doesn't do it with Source Han Mono is because this font _does_ have an Italic version, but only for the Latin glyphs, not for CJK. If you type something like "Hello" instead of "你好，思源等宽" then you will see that Italic is working as intended for this font. If you want it to act like the other examples you show then you need to delete the Italic fonts from your Fonts folder. Then when you choose Italic you will get the same result as the others you show.

**Comment by cody1996** [comment]
@punchcutter Got it. Thanks again.
